### PR TITLE
React Hooks and fully customizable and many more 🎊🎉

### PR DESCRIPTION
**Pull request by kuraydev**
- [x] I completely converted to the functional component
- [x] React Hooks is integrated
- [x] Almost fully customizable now
- [x] Updated the react-native-video to the latest version (currently 5.0.2)
- [x] Updated the react-native-slider to the latest version
- [x] Updated the whole example with the latest react native and react (RN 0.61.4)
- [x] Cleaned some code but it still needs to upgraded to Typescript
- [ ] Did NOT update the README :(

### CODE REVIEW

**Comment by WrathChaos** [comment]
@charliesbot

**Comment by rodrigowpl** [comment]
Hey! Nice work in this library!

Any plans to merge it?

Thanks

**Comment by juddey** [comment]
You're doing some good work around the react-native  community  @WrathChaos

**Comment by WrathChaos** [comment]
> You're doing some good work around the react-native community @WrathChaos

Ah thank you so much for these kind words sir 🥺 Really touches me 🥰

**Pull request closed without merging**
